In [5]:
import numpy as np

In [7]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [9]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [10]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [13]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
np.arange(1,31,5)

array([ 1,  6, 11, 16, 21, 26])

In [15]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [21]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [22]:
Simple_list=(["kalp","Jeel","Janmesh","Jaini"])
np.array(Simple_list)

array(['kalp', 'Jeel', 'Janmesh', 'Jaini'], dtype='<U7')

In [23]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [41]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [42]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(3,5)

array([[0.92902961, 0.33634196, 0.29388775, 0.45094356, 0.05622176],
       [0.75348724, 0.91252138, 0.10881009, 0.56156821, 0.33717589],
       [0.50067021, 0.33398194, 0.67187837, 0.15830588, 0.87803139]])

In [27]:
arr=np.random.randn(2,4)
arr

array([[-1.59858392,  0.22599783,  0.70693313, -1.05205885],
       [-1.04180665,  0.63110371, -0.06635338, -0.20656581]])

In [28]:
np.random.randint(2,100)

53

In [30]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [32]:
rand_array=np.random.randint(0,100,20)
rand_array

array([38, 19, 27, 84, 84, 47,  6, 96, 78, 82, 86, 69, 43, 68, 49,  6, 95,
       76, 39, 90])

In [33]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [34]:
rand_array.max()

96

In [35]:
rand_array.argmax()

7

In [37]:
a=np.random.rand(2,3)
a

array([[0.04632644, 0.30444769, 0.04115759],
       [0.87398921, 0.42619159, 0.30355539]])

In [44]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [47]:
sample_array[0]

10

In [49]:
a=np.random.rand(2,3)
a

array([[0.49968536, 0.25876149, 0.19287233],
       [0.65417296, 0.43871726, 0.94683691]])

In [50]:
a.T

array([[0.49968536, 0.65417296],
       [0.25876149, 0.43871726],
       [0.19287233, 0.94683691]])

In [51]:
sample_array[2:5]

array([12, 13, 14])

In [52]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [54]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [55]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [57]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [58]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

# Two-Dimentionsal array

In [61]:
import numpy as np

In [63]:
sample_matrix=np.array([[50,21,1,40],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 21,  1, 40],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [64]:
sample_matrix[1,2]

21

In [65]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [67]:
sample_matrix[2]

array([56, 76, 24,  7])

# Selection techniques

In [2]:
import numpy as np

In [3]:
sample_array=np.arange(1,20)

In [4]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [7]:
np.exe(sample_array)

AttributeError: module 'numpy' has no attribute 'exe'

In [8]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [9]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [10]:
np.max(sample_array)

19

In [11]:
np.min(sample_array)

1

In [12]:
np.argmax(sample_array)

18

In [13]:
np.argmin(sample_array)

0

In [14]:
np.std(sample_array)

5.477225575051661

In [15]:
np.var(sample_array)

30.0

In [16]:
np.mean(sample_array)

10.0

In [17]:
array=np.random.randn(3,4)

In [18]:
array

array([[ 0.82698846, -0.31697491, -0.55366098, -0.26505736],
       [-1.10163665,  0.65217078, -0.69300521, -0.37672147],
       [ 0.534925  , -0.53706624, -1.15204949,  0.30076955]])

In [21]:
np.round(array,decimals=2)

array([[ 0.83, -0.32, -0.55, -0.27],
       [-1.1 ,  0.65, -0.69, -0.38],
       [ 0.53, -0.54, -1.15,  0.3 ]])

In [25]:
sports=np.array(['golf','cricket','football','Basketball'])
np.unique(sports)

array(['Basketball', 'cricket', 'football', 'golf'], dtype='<U10')

### Pandas

In [26]:
import numpy as np
import pandas as pd

In [27]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [28]:
sports2=pd.Series([11,2,3,4],index=['cricket','football','basketball','golf'])
sports2

cricket       11
football       2
basketball     3
golf           4
dtype: int64

In [29]:
sports1+sports2

cricket       12
football       4
basketball     6
golf           8
dtype: int64

In [30]:
import numpy as np
import pandas as pd

In [32]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.886958  0.568532  0.763887  0.020056  0.113868
B  0.011423  0.074529  0.709527  0.488018  0.626559
C  0.019659  0.690580  0.112538  0.585790  0.280298
D  0.959325  0.568457  0.602504  0.090682  0.231170
E  0.057827  0.078084  0.122228  0.521082  0.518000
F  0.136495  0.334846  0.077509  0.806623  0.545715
G  0.404729  0.554483  0.152293  0.103197  0.191858
H  0.841563  0.255991  0.640600  0.730236  0.729788

In [33]:
df1["Score1"]

A    0.886958
B    0.011423
C    0.019659
D    0.959325
E    0.057827
F    0.136495
G    0.404729
H    0.841563
Name: Score1, dtype: float64

In [35]:
df1[["Score1","Score2","Score3"]]

Score1    Score2    Score3
A  0.886958  0.568532  0.763887
B  0.011423  0.074529  0.709527
C  0.019659  0.690580  0.112538
D  0.959325  0.568457  0.602504
E  0.057827  0.078084  0.122228
F  0.136495  0.334846  0.077509
G  0.404729  0.554483  0.152293
H  0.841563  0.255991  0.640600

In [37]:
df1["Score6"]=df1['Score1']+df1['Score2']
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.886958  0.568532  0.763887  0.020056  0.113868  1.455490
B  0.011423  0.074529  0.709527  0.488018  0.626559  0.085952
C  0.019659  0.690580  0.112538  0.585790  0.280298  0.710239
D  0.959325  0.568457  0.602504  0.090682  0.231170  1.527781
E  0.057827  0.078084  0.122228  0.521082  0.518000  0.135910
F  0.136495  0.334846  0.077509  0.806623  0.545715  0.471341
G  0.404729  0.554483  0.152293  0.103197  0.191858  0.959212
H  0.841563  0.255991  0.640600  0.730236  0.729788  1.097554

In [38]:
df2={'ID':['101','102','103','104','105'],'Name':['Kalp','Jeel','Janmesh','Jaini','Pratham'],'Profit':[20,30,40,50,60]}
df=pd.DataFrame(df2)
df

ID     Name  Profit
0  101     Kalp      20
1  102     Jeel      30
2  103  Janmesh      40
3  104    Jaini      50
4  105  Pratham      60

In [39]:
df["ID"]

0    101
1    102
2    103
3    104
4    105
Name: ID, dtype: object

In [40]:
df[["ID","Name","Profit"]]

ID     Name  Profit
0  101     Kalp      20
1  102     Jeel      30
2  103  Janmesh      40
3  104    Jaini      50
4  105  Pratham      60

In [41]:
df=df.drop("ID",axis=1)

In [42]:
df

Name  Profit
0     Kalp      20
1     Jeel      30
2  Janmesh      40
3    Jaini      50
4  Pratham      60

In [44]:
df.drop(3)


Name  Profit
0     Kalp      20
1     Jeel      30
2  Janmesh      40
4  Pratham      60

In [46]:
df

Name  Profit
0     Kalp      20
1     Jeel      30
2  Janmesh      40
3    Jaini      50
4  Pratham      60