In [5]:
import numpy as np

In [7]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [9]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [10]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [13]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
np.arange(1,31,5)

array([ 1,  6, 11, 16, 21, 26])

In [15]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [21]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [22]:
Simple_list=(["kalp","Jeel","Janmesh","Jaini"])
np.array(Simple_list)

array(['kalp', 'Jeel', 'Janmesh', 'Jaini'], dtype='<U7')

In [23]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [41]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [42]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(3,5)

array([[0.92902961, 0.33634196, 0.29388775, 0.45094356, 0.05622176],
       [0.75348724, 0.91252138, 0.10881009, 0.56156821, 0.33717589],
       [0.50067021, 0.33398194, 0.67187837, 0.15830588, 0.87803139]])

In [27]:
arr=np.random.randn(2,4)
arr

array([[-1.59858392,  0.22599783,  0.70693313, -1.05205885],
       [-1.04180665,  0.63110371, -0.06635338, -0.20656581]])

In [28]:
np.random.randint(2,100)

53

In [30]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [32]:
rand_array=np.random.randint(0,100,20)
rand_array

array([38, 19, 27, 84, 84, 47,  6, 96, 78, 82, 86, 69, 43, 68, 49,  6, 95,
       76, 39, 90])

In [33]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [34]:
rand_array.max()

96

In [35]:
rand_array.argmax()

7

In [37]:
a=np.random.rand(2,3)
a

array([[0.04632644, 0.30444769, 0.04115759],
       [0.87398921, 0.42619159, 0.30355539]])

In [44]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [47]:
sample_array[0]

10

In [49]:
a=np.random.rand(2,3)
a

array([[0.49968536, 0.25876149, 0.19287233],
       [0.65417296, 0.43871726, 0.94683691]])

In [50]:
a.T

array([[0.49968536, 0.65417296],
       [0.25876149, 0.43871726],
       [0.19287233, 0.94683691]])

In [51]:
sample_array[2:5]

array([12, 13, 14])

In [52]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [54]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [55]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [57]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [58]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

# Two-Dimentionsal array

In [61]:
import numpy as np

In [63]:
sample_matrix=np.array([[50,21,1,40],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 21,  1, 40],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [64]:
sample_matrix[1,2]

21

In [65]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [67]:
sample_matrix[2]

array([56, 76, 24,  7])

# Selection techniques